useGroupedVersion: true

version_info_list_js:
  - value: latest version(3.2.30)
  - value: 3.x
    child:
      - 3.0.30
  - value: 2.x
    child:
      - 2.2.31
      - 2.2.30
      - 2.2.11
      - 2.2.10
      - 2.2.4
      - 2.2.2
      - 2.2.1
      - 2.2.0
