useGroupedVersion: true

version_info_list_web:
  - value: latest version
  - value: 3.x
    child:
      - 3.0.20(latest)
  - value: 2.x
    child:
      - 2.2.31
      - 2.2.30
      - 2.2.11
      - 2.2.10
      - 2.2.4
      - 2.2.2
      - 2.2.1
      - 2.2.0
